### ISSUE TITLE
构建报错

### ISSUE THREAD

**Issue by q383186554** [Shiotsukikaedesari/three-vis-display-editor#14]
文件夹下有dist压缩包，压缩包大小为0

ERROR [HttpExecptionFilter.catch] NotFoundException: Cannot GET /app/5/dist
NotFoundException: Cannot GET /app/5/dist

**Comment by Shiotsukikaedesari** [comment]
压缩包大小为零是初始的时候会生成一个0大小的压缩包文件作为占位

**Comment by Shiotsukikaedesari** [comment]
> 文件夹下有dist压缩包，压缩包大小为0
> 
> ERROR [HttpExecptionFilter.catch] NotFoundException: Cannot GET /app/5/dist NotFoundException: Cannot GET /app/5/dist
压缩包大小为零是初始的时候会生成一个0大小的压缩包文件作为占位

**Comment by Shiotsukikaedesari** [comment]
> 文件夹下有dist压缩包，压缩包大小为0
> 
> ERROR [HttpExecptionFilter.catch] NotFoundException: Cannot GET /app/5/dist NotFoundException: Cannot GET /app/5/dist

压缩包大小为零是因为初始的时候会生成一个0大小的占位文件

**Comment by q383186554** [comment]
构建错误提示如下

: [3]
Error: Command failed: npm run build
'vue-cli-service' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

    at ChildProcess.exithandler (node:child_process:400:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1093:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
