### ISSUE TITLE
场景选择物体和实际左侧树结构不一致

### ISSUE THREAD

**Issue by 1340277433** [Shiotsukikaedesari/three-vis-display-editor#27]
![image](https://user-images.githubusercontent.com/25837625/217410814-51c6ba4c-27a6-4c03-8d58-a19f892f47e9.png)

**Comment by 1340277433** [comment]
![image](https://user-images.githubusercontent.com/25837625/217411667-bffc964a-9e5a-4d6c-96bf-e356e45082a9.png)

**Comment by Shiotsukikaedesari** [comment]
引擎缺少插件，解决版本："@vis-three/modeling-engine-support": "^0.5.4"，最新版注意更新依赖
