### ISSUE TITLE
每个物体的初始化位置为同一位置，是否能默认沿某一个轴方向添加

### ISSUE THREAD

**Issue by 1340277433** [Shiotsukikaedesari/three-vis-display-editor#28]
![image](https://user-images.githubusercontent.com/25837625/217411000-d8f880d3-d6ac-40b9-9e52-52c138288a79.png)

**Comment by Shiotsukikaedesari** [comment]
初始化问题，不同的业务场景有不同的需求要求，可以根据自身的业务需求修改。
