### ISSUE TITLE
上传模型的格式是什么？

### ISSUE THREAD

**Issue by cfxisrich** [Shiotsukikaedesari/three-vis-display-editor#37]
我看视频里上传模型库是一个zip文件，对文件的层级和内容有要求吗？我有试过编辑完后构建下载，然后再上传会报错
![image](https://github.com/Shiotsukikaedesari/three-vis-display-editor/assets/89836473/48e07bd8-30a3-422a-bd4d-2b9a08126d39)
如果想上传一个gltf文件及threejs文件，应该怎么上传呢

**Comment by Shiotsukikaedesari** [comment]
此issue已归类为“提问”标签，issue流程请参照readme.md进行.

**Comment by Shiotsukikaedesari** [comment]
此用户以完成相关issue：https://gitee.com/Shiotsukikaedesari/three-vis-display-editor/issues/I88EZC
