### ISSUE TITLE
平移功能是针对模型的平移吗？场景是否有拖拽功能？如果有该怎么使用呢？

### ISSUE THREAD

**Issue by cfxisrich** [Shiotsukikaedesari/three-vis-display-editor#38]

**Comment by Shiotsukikaedesari** [comment]
此issue已归类为“提问”标签，issue流程请参照readme.md进行.

**Comment by Shiotsukikaedesari** [comment]
平移功能是使用的three.js transformControls作为插件，所以是针对选中3D物体的position做移动，目前没有场景拖拽功能，因为编辑器暂时没有这部分的需求。
