### ISSUE TITLE
display-service 编辑器后台服务启动报错

### ISSUE THREAD

**Issue by nanfenghuiyi** [Shiotsukikaedesari/three-vis-display-editor#41]
![QQ图片20230909222310](https://github.com/Shiotsukikaedesari/three-vis-display-editor/assets/51777595/bb7fa4a2-1eaa-4eaa-80e3-861fd195e274)

**Comment by Shiotsukikaedesari** [comment]
此issue已归类为“提问”标签，请进入赞助、合作、通知群进行 issue 完成度与回报模式确认，QQ：586362945，详细issue流程请参照README.md。

**Comment by nanfenghuiyi** [comment]
mysql未启动，已处理
