### ISSUE TITLE
three-vis-display-editor启动后黑屏，控制栏有个报错

### ISSUE THREAD

**Issue by nanfenghuiyi** [Shiotsukikaedesari/three-vis-display-editor#42]
![image](https://github.com/Shiotsukikaedesari/three-vis-display-editor/assets/51777595/4202a8ee-1891-43c2-ba60-a53700b9c2df)

分支master，后端服务已启动
![image](https://github.com/Shiotsukikaedesari/three-vis-display-editor/assets/51777595/980a1c64-bde5-4b81-81d1-c35d95d2cf15)

**Comment by Shiotsukikaedesari** [comment]
此issue已归类为“提问”标签，请进入赞助、合作、通知群进行 issue 完成度与回报模式确认，QQ：586362945，详细issue流程请参照README.md。

**Comment by Shiotsukikaedesari** [comment]
1、这应该是一个前端问题。
2、虽然没有给出报错的定位代码，也就是vis-three.middleware.es.js报错的定位代码，但是作者推测应该是EventGeneratorManager.register函数装载时出现了问题。
3、EventGeneratorManager可以通过外部动态注入事件方法，编辑器在初始化的时候预先通过vis-three框架预置好的事件库：@vis-three/library-event进行事件注册。
4、由于版本调整，最近一批的版本包在es导出时将事件集合通过export default导出，其他的有用成员通过export自定义导出，所以可能是这部分问题在旧版本引入上产生了影响。


解决方法：
1、更新@vis-three/library-event（或降级，不推荐）
2、在engine初始化的位置或者说EventGeneratorManager.register进行注册处理的位置，修改@vis-three/library-event的导入模式。
3、重启服务进行报错验证。
