### ISSUE TITLE
第一次启动项目后，网格，辅助坐标系报错

### ISSUE THREAD

**Issue by cfxisrich** [Shiotsukikaedesari/three-vis-display-editor#45]
![image](https://github.com/vis-three/scene-editor/assets/89836473/abd4368d-8f63-4808-bc63-3eb07add23e9)
![image](https://github.com/vis-three/scene-editor/assets/89836473/727b4eed-616a-4260-a3ce-7ff20abdf53d)

**Comment by Shiotsukikaedesari** [comment]
此issue已归类为“提问”标签，请进入赞助、合作、通知群进行 issue 完成度与回报模式确认，QQ：586362945，详细issue流程请参照README.md。

**Comment by Shiotsukikaedesari** [comment]
1、第一个报错是由于新版插件和项目使用冲突导致的，修复可以参考@vis-three/plugin-axes-helper文档：https://vis-three.github.io/docs/library/plugins/plugin-axes-helper.html
2、第二和第四个报错是由于新版本中间层和项目使用冲突导致的，修复可以参考@vis-three/middleware，或者官方文档：https://vis-three.github.io/docs/start/combine.html
3、第三个报错是由于新版插件和项目使用冲突导致的，修复可以参考@vis-three/plugin-grid-helper文档：https://vis-three.github.io/docs/library/plugins/plugin-grid-helper.html

**Comment by 285858315** [comment]
@Shiotsukikaedesari 有微信群吗？或者钉钉？

**Comment by Shiotsukikaedesari** [comment]
> @Shiotsukikaedesari 有微信群吗？或者钉钉？

群聊请查看项目README.md文档。

**Comment by cfxisrich** [comment]
没有加微信群，钉钉也没有，后面被其他的事情叫去先忙了，然后还没有去修复那几个，要等国庆后才能去研究三维了，害，国庆后我去申请只做三维，不然停一下做一下太烦了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vis-three/scene-editor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月19日(星期二) 下午2:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [vis-three/scene-editor] 第一次启动项目后，网格，辅助坐标系报错 (Issue #45)





  
@Shiotsukikaedesari 有微信群吗？或者钉钉？
  
群聊请查看项目README.md文档。

**Comment by cfxisrich** [comment]
成功修复之后我提交到项目README.md文档中。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vis-three/scene-editor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月19日(星期二) 下午2:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [vis-three/scene-editor] 第一次启动项目后，网格，辅助坐标系报错 (Issue #45)





  
@Shiotsukikaedesari 有微信群吗？或者钉钉？
  
群聊请查看项目README.md文档。

**Comment by ilovejiabao** [comment]
请问上述的解决方案，是修改vis-three代码还是修改编辑器的代码。 根据解决方案链接点进去不太清楚如何修改

**Comment by Shiotsukikaedesari** [comment]
> 请问上述的解决方案，是修改vis-three代码还是修改编辑器的代码。 根据解决方案链接点进去不太清楚如何修改

将vis-three类比成vue框架，现在框架插件版本和项目使用版本出现冲突，而且已经有插件文档的前提下，一般会如何处理？思考思考。
