### ISSUE TITLE
进入编辑器后，控制台有报错

### ISSUE THREAD

**Issue by nanfenghuiyi** [Shiotsukikaedesari/three-vis-display-editor#46]
![image](https://github.com/vis-three/scene-editor/assets/51777595/b80b5ac0-3077-4657-b481-9217800d8fe5)  
报错文件是store/index.js 
notifyAll(state) {
      Object.values(MODULETYPE).forEach((module) => {
        this.commit(`${module}/notify`);
      });
    },

![image](https://github.com/vis-three/scene-editor/assets/51777595/59a5dc9d-ad6f-438a-91c0-8a479f53f308)
报错文件是 vue.esm.js
![image](https://github.com/vis-three/scene-editor/assets/51777595/e8d5f68b-04f9-4e98-907e-5812d11dbd81)

![image](https://github.com/vis-three/scene-editor/assets/51777595/6eded9b1-ab46-4f24-9998-69ee96bcaab3)
报错文件时 auxiliaryDisplay.vue
showHelper: {
      handler(newVal) {
        this.connector.setObjectHelper(newVal);
      },
      immediate: true,
    },

当前添加模型，灯光等，结构处无可点击项
![image](https://github.com/vis-three/scene-editor/assets/51777595/ebd03025-4e40-43c7-9993-2319e269fc93)

**Comment by 285858315** [comment]
+1

**Comment by Shiotsukikaedesari** [comment]
store报错问题，是由于@vis-three/library-module新增了很多模块，然后store本身写法缺少了相关模块导致，修复可以补全缺少模块，或者换一种store写法。

**Comment by Shiotsukikaedesari** [comment]
其他问题参考： #45
