### ISSUE TITLE
动画功能优化

### ISSUE THREAD

**Issue by waded3** [Shiotsukikaedesari/three-vis-display-editor#48]
在B站上看到作者演示的加载士兵动画及动画交互的小案例，想要在本项目上实现完整动画功能（包括脚本动画和混合器动画）。

**Comment by Shiotsukikaedesari** [comment]
此issue已归类为“新增”标签，请进入赞助、合作、通知群进行 issue 完成度与回报模式确认，QQ：586362945，详细issue流程请参照README.md。

**Comment by Shiotsukikaedesari** [comment]
这块功能对于初学者来说很有难度，建议先熟悉vis-three框架，然后熟悉动画相关模块的配置@vis-three/module-animation，然后根据配置和需求的交互功能进行结合开发。开发期和调试期都会比较长。
