### ISSUE TITLE
开发模式下没有问题，但是打包时报错

### ISSUE THREAD

**Issue by sheerhr** [Shiotsukikaedesari/three-vis-display-editor#49]
开发时正常
  App running at:
  - Local:   http://localhost:8080
  - Network: http://localhost:8080
但打包时报错
  error  

js/app~c714bc7b.91d70b9c.js from Terser
"module" is redeclared [js/app~c714bc7b.91d70b9c.js:284,6]

 ERROR  Build failed with errors.
 ELIFECYCLE  Command failed with exit code 1.

在分支0.3.x下进行的

**Comment by Shiotsukikaedesari** [comment]
此issue已归类为“提问”标签，请进入赞助、合作、通知群进行 issue 完成度与回报模式确认，QQ：586362945，详细issue流程请参照README.md。
