### ISSUE TITLE
模型整体缩放后，再使用变换控制器控制模型的一部分出现偏差

### ISSUE THREAD

**Issue by cannnndy** [Shiotsukikaedesari/three-vis-display-editor#50]
### 问题描述

```bash
如导入的模型整体缩放后，再用变换控制器移动模型的一部分，控制器移动距离与模型的移动距离出现偏差，移动整个模型没问题
```

### 问题或报错截图

移动前
![image](https://github.com/vis-three/scene-editor/assets/22367347/8cd8c420-ed90-4f1c-8fe0-0d0295c3c4e8)

移动时
![image](https://github.com/vis-three/scene-editor/assets/22367347/a56c13f2-ab94-4d70-a49b-d8a93c1b5ab4)

### 运行环境

```bash
系统: windows@10
浏览器： chrome@131
脚手架： vite@2.9.15
node: 14.20.0
```

**Comment by Shiotsukikaedesari** [comment]
这个应该是vis-three的transofromControlsPlugin在影响存在父级的物体时重复应用矩阵造成的，需要等待框架插件更新。

**Comment by Shiotsukikaedesari** [comment]
0.6.15版本已解决。
